// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace UITests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// TestCoreFunctions - Use 'TestCoreFunctionsParams' to pass parameters into this method.
        /// </summary>
        public void TestCoreFunctions()
        {
            #region Variable Declarations
            WinTree uITreeViewTree = this.UIВыберитетекстовыйфайWindow.UITreeViewWindow.UITreeViewTree;
            WinList uIItemsViewList = this.UIВыберитетекстовыйфайWindow.UIItemsViewWindow.UIItemsViewList;
            WinEdit uITextBox1Edit = this.UIМинималистичныйтекстWindow.UITextBox1Window.UITextBox1Edit;
            WinEdit uIFilenameEdit = this.UIВыберитекудасохранитWindow.UIItemWindow.UIFilenameEdit;
            WinComboBox uIFilenameComboBox = this.UIВыберитекудасохранитWindow.UIDetailsPanePane.UIFilenameComboBox;
            WinList uIItemsViewList1 = this.UIВыберитекудасохранитWindow.UIItemsViewWindow.UIItemsViewList;
            #endregion

            // To test Windows Store apps, use the Coded UI Test project template for Windows Store apps under the Windows Store node.

            // To test Windows Store apps, use the Coded UI Test project template for Windows Store apps under the Windows Store node.

            // To test Windows Store apps, use the Coded UI Test project template for Windows Store apps under the Windows Store node.

            // Click 'Tree View' tree
            Mouse.Click(uITreeViewTree, new Point(304, 519));

            // Click 'Items View' list box
            Mouse.Click(uIItemsViewList, new Point(873, 590));

            // To test Windows Store apps, use the Coded UI Test project template for Windows Store apps under the Windows Store node.

            // To test Windows Store apps, use the Coded UI Test project template for Windows Store apps under the Windows Store node.

            // Type the following paragraph in 'textBox1' text box 
            //'Мой текст
            //Add some text'
            uITextBox1Edit.Text = this.TestCoreFunctionsParams.UITextBox1EditText;

            // To test Windows Store apps, use the Coded UI Test project template for Windows Store apps under the Windows Store node.

            // To test Windows Store apps, use the Coded UI Test project template for Windows Store apps under the Windows Store node.

            // Type 'Alt + {LShiftKey}' in 'File name:' text box
            Keyboard.SendKeys(uIFilenameEdit, this.TestCoreFunctionsParams.UIFilenameEditSendKeys, ModifierKeys.Alt);

            // Select 'ДругойФайл' in 'File name:' combo box
            uIFilenameComboBox.EditableItem = this.TestCoreFunctionsParams.UIFilenameComboBoxEditableItem;

            // Click 'Items View' list box
            Mouse.Click(uIItemsViewList1, new Point(861, 586));
        }
        
        #region Properties
        public virtual TestCoreFunctionsParams TestCoreFunctionsParams
        {
            get
            {
                if ((this.mTestCoreFunctionsParams == null))
                {
                    this.mTestCoreFunctionsParams = new TestCoreFunctionsParams();
                }
                return this.mTestCoreFunctionsParams;
            }
        }
        
        public UIВыберитетекстовыйфайWindow UIВыберитетекстовыйфайWindow
        {
            get
            {
                if ((this.mUIВыберитетекстовыйфайWindow == null))
                {
                    this.mUIВыберитетекстовыйфайWindow = new UIВыберитетекстовыйфайWindow();
                }
                return this.mUIВыберитетекстовыйфайWindow;
            }
        }
        
        public UIМинималистичныйтекстWindow UIМинималистичныйтекстWindow
        {
            get
            {
                if ((this.mUIМинималистичныйтекстWindow == null))
                {
                    this.mUIМинималистичныйтекстWindow = new UIМинималистичныйтекстWindow();
                }
                return this.mUIМинималистичныйтекстWindow;
            }
        }
        
        public UIВыберитекудасохранитWindow UIВыберитекудасохранитWindow
        {
            get
            {
                if ((this.mUIВыберитекудасохранитWindow == null))
                {
                    this.mUIВыберитекудасохранитWindow = new UIВыберитекудасохранитWindow();
                }
                return this.mUIВыберитекудасохранитWindow;
            }
        }
        #endregion
        
        #region Fields
        private TestCoreFunctionsParams mTestCoreFunctionsParams;
        
        private UIВыберитетекстовыйфайWindow mUIВыберитетекстовыйфайWindow;
        
        private UIМинималистичныйтекстWindow mUIМинималистичныйтекстWindow;
        
        private UIВыберитекудасохранитWindow mUIВыберитекудасохранитWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TestCoreFunctions'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class TestCoreFunctionsParams
    {
        
        #region Fields
        /// <summary>
        /// Type the following paragraph in 'textBox1' text box 
        ///'Мой текст
        ///Add some text'
        /// </summary>
        public string UITextBox1EditText = "Мой текст\r\nAdd some text";
        
        /// <summary>
        /// Type 'Alt + {LShiftKey}' in 'File name:' text box
        /// </summary>
        public string UIFilenameEditSendKeys = "{LShiftKey}";
        
        /// <summary>
        /// Select 'ДругойФайл' in 'File name:' combo box
        /// </summary>
        public string UIFilenameComboBoxEditableItem = "ДругойФайл";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIВыберитетекстовыйфайWindow : WinWindow
    {
        
        public UIВыберитетекстовыйфайWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Выберите текстовый файл...";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Выберите текстовый файл...");
            #endregion
        }
        
        #region Properties
        public UITreeViewWindow UITreeViewWindow
        {
            get
            {
                if ((this.mUITreeViewWindow == null))
                {
                    this.mUITreeViewWindow = new UITreeViewWindow(this);
                }
                return this.mUITreeViewWindow;
            }
        }
        
        public UIItemsViewWindow UIItemsViewWindow
        {
            get
            {
                if ((this.mUIItemsViewWindow == null))
                {
                    this.mUIItemsViewWindow = new UIItemsViewWindow(this);
                }
                return this.mUIItemsViewWindow;
            }
        }
        #endregion
        
        #region Fields
        private UITreeViewWindow mUITreeViewWindow;
        
        private UIItemsViewWindow mUIItemsViewWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UITreeViewWindow : WinWindow
    {
        
        public UITreeViewWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Выберите текстовый файл...");
            #endregion
        }
        
        #region Properties
        public WinTree UITreeViewTree
        {
            get
            {
                if ((this.mUITreeViewTree == null))
                {
                    this.mUITreeViewTree = new WinTree(this);
                    #region Search Criteria
                    this.mUITreeViewTree.WindowTitles.Add("Выберите текстовый файл...");
                    #endregion
                }
                return this.mUITreeViewTree;
            }
        }
        #endregion
        
        #region Fields
        private WinTree mUITreeViewTree;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemsViewWindow : WinWindow
    {
        
        public UIItemsViewWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Items View";
            this.WindowTitles.Add("Выберите текстовый файл...");
            #endregion
        }
        
        #region Properties
        public WinList UIItemsViewList
        {
            get
            {
                if ((this.mUIItemsViewList == null))
                {
                    this.mUIItemsViewList = new WinList(this);
                    #region Search Criteria
                    this.mUIItemsViewList.SearchProperties[WinList.PropertyNames.Name] = "Items View";
                    this.mUIItemsViewList.WindowTitles.Add("Выберите текстовый файл...");
                    #endregion
                }
                return this.mUIItemsViewList;
            }
        }
        #endregion
        
        #region Fields
        private WinList mUIItemsViewList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIМинималистичныйтекстWindow : WinWindow
    {
        
        public UIМинималистичныйтекстWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Минималистичный текстовый редактор";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Минималистичный текстовый редактор");
            #endregion
        }
        
        #region Properties
        public UITextBox1Window UITextBox1Window
        {
            get
            {
                if ((this.mUITextBox1Window == null))
                {
                    this.mUITextBox1Window = new UITextBox1Window(this);
                }
                return this.mUITextBox1Window;
            }
        }
        #endregion
        
        #region Fields
        private UITextBox1Window mUITextBox1Window;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UITextBox1Window : WinWindow
    {
        
        public UITextBox1Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "textBox1";
            this.WindowTitles.Add("Минималистичный текстовый редактор");
            #endregion
        }
        
        #region Properties
        public WinEdit UITextBox1Edit
        {
            get
            {
                if ((this.mUITextBox1Edit == null))
                {
                    this.mUITextBox1Edit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITextBox1Edit.WindowTitles.Add("Минималистичный текстовый редактор");
                    #endregion
                }
                return this.mUITextBox1Edit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITextBox1Edit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIВыберитекудасохранитWindow : WinWindow
    {
        
        public UIВыберитекудасохранитWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Выберите куда сохранить...";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Выберите куда сохранить...");
            #endregion
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIDetailsPanePane UIDetailsPanePane
        {
            get
            {
                if ((this.mUIDetailsPanePane == null))
                {
                    this.mUIDetailsPanePane = new UIDetailsPanePane(this);
                }
                return this.mUIDetailsPanePane;
            }
        }
        
        public UIItemsViewWindow1 UIItemsViewWindow
        {
            get
            {
                if ((this.mUIItemsViewWindow == null))
                {
                    this.mUIItemsViewWindow = new UIItemsViewWindow1(this);
                }
                return this.mUIItemsViewWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        
        private UIDetailsPanePane mUIDetailsPanePane;
        
        private UIItemsViewWindow1 mUIItemsViewWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1001";
            this.WindowTitles.Add("Выберите куда сохранить...");
            #endregion
        }
        
        #region Properties
        public WinEdit UIFilenameEdit
        {
            get
            {
                if ((this.mUIFilenameEdit == null))
                {
                    this.mUIFilenameEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIFilenameEdit.SearchProperties[WinEdit.PropertyNames.Name] = "File name:";
                    this.mUIFilenameEdit.WindowTitles.Add("Выберите куда сохранить...");
                    #endregion
                }
                return this.mUIFilenameEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIFilenameEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDetailsPanePane : WinPane
    {
        
        public UIDetailsPanePane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Details Pane";
            this.WindowTitles.Add("Выберите куда сохранить...");
            #endregion
        }
        
        #region Properties
        public WinComboBox UIFilenameComboBox
        {
            get
            {
                if ((this.mUIFilenameComboBox == null))
                {
                    this.mUIFilenameComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUIFilenameComboBox.SearchProperties[WinComboBox.PropertyNames.Name] = "File name:";
                    this.mUIFilenameComboBox.WindowTitles.Add("Выберите куда сохранить...");
                    #endregion
                }
                return this.mUIFilenameComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUIFilenameComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemsViewWindow1 : WinWindow
    {
        
        public UIItemsViewWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Items View";
            this.WindowTitles.Add("Выберите куда сохранить...");
            #endregion
        }
        
        #region Properties
        public WinList UIItemsViewList
        {
            get
            {
                if ((this.mUIItemsViewList == null))
                {
                    this.mUIItemsViewList = new WinList(this);
                    #region Search Criteria
                    this.mUIItemsViewList.SearchProperties[WinList.PropertyNames.Name] = "Items View";
                    this.mUIItemsViewList.WindowTitles.Add("Выберите куда сохранить...");
                    #endregion
                }
                return this.mUIItemsViewList;
            }
        }
        #endregion
        
        #region Fields
        private WinList mUIItemsViewList;
        #endregion
    }
}
